"""Regenerate the property-vocabulary table in data/claims/README.md.

The property LIST is derived from the shipped gold-standard YAMLs (never
hand-synced); the one-line meanings live in MEANINGS below. The script fails
loudly if a YAML uses a property with no meaning here, or if MEANINGS carries
a property no YAML uses — either way the fix is explicit.

Run:  python scripts/gen_claims_vocab.py
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CLAIMS_DIR = ROOT / "data" / "claims"
README = CLAIMS_DIR / "README.md"

BEGIN = "<!-- vocabulary:begin (generated by scripts/gen_claims_vocab.py) -->"
END = "<!-- vocabulary:end -->"

MEANINGS = {
    "nominal_capacity_ah": "rated/nominal capacity",
    "rated_capacity_ah": "rated capacity where stated separately from nominal",
    "minimum_capacity_ah": "guaranteed minimum capacity",
    "nominal_voltage_v": "nominal cell voltage",
    "charge_voltage_v": "CV charge voltage (± tolerance in conditions)",
    "max_charge_voltage_v": "maximum allowed charge voltage",
    "discharge_cutoff_v": "end-of-discharge voltage",
    "std_charge_current_a": "standard charge current",
    "std_charge_time_h": "standard charge duration",
    "max_charge_current_a": "maximum allowed charge current",
    "fast_charge_current_a": "fast/max charge rate",
    "std_discharge_current_a": "standard discharge current",
    "fast_discharge_current_a": "fast discharge rate",
    "max_cont_discharge_a": "max continuous discharge current",
    "cycle_life_cycles": "cycle life claim (conditions are essential)",
    "cycle_life_retention_pct": "capacity retention the cycle-life claim is defined at",
    "capacity_retention_at_temp_pct": "capacity retained at a stated temperature",
    "storage_capacity_remaining_pct": "capacity remaining after stated storage",
    "storage_capacity_recovery_pct": "capacity recoverable after stated storage",
    "mass_g": "cell mass",
    "charge_temp_range_c": "allowed charge temperature range `[lo, hi]`",
    "discharge_temp_range_c": "allowed discharge temperature range `[lo, hi]`",
    "operating_temp_range_c": "allowed operating temperature range `[lo, hi]`",
    "storage_temp_range_c": "allowed storage temperature range `[lo, hi]`",
    "internal_impedance_mohm": "AC impedance (1 kHz typical)",
    "gravimetric_energy_density_wh_kg": "energy density by mass",
    "volumetric_energy_density_wh_l": "energy density by volume",
}


def used_properties() -> list[str]:
    props: set[str] = set()
    for p in sorted(CLAIMS_DIR.glob("*.yaml")):
        doc = yaml.safe_load(p.read_text())
        props.update(c["property"] for c in doc["claims"])
    return sorted(props)


def main() -> None:
    props = used_properties()
    missing = [p for p in props if p not in MEANINGS]
    unused = [p for p in MEANINGS if p not in props]
    if missing:
        raise SystemExit(f"properties in YAMLs with no meaning defined: {missing}")
    if unused:
        raise SystemExit(f"meanings defined for properties no YAML uses: {unused}")

    lines = [BEGIN, "", "| property | meaning |", "|---|---|"]
    lines += [f"| `{p}` | {MEANINGS[p]} |" for p in props]
    lines += ["", END]
    table = "\n".join(lines)

    text = README.read_text()
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), table,
                      text, flags=re.S)
    else:
        raise SystemExit(f"markers not found in {README} — add {BEGIN} / {END}")
    README.write_text(text)
    print(f"[gen_claims_vocab] {len(props)} properties -> {README}")


if __name__ == "__main__":
    main()
